server:
  port: 8099
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    context-path: /

spring:
  #配置freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    prefer-file-system-access: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
  mvc:
    static-path-pattern: /WEB-INF/**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
      enabled: true
  application:
    name: projects-netty                         # 指定服务名称  SERVICE-CORE